baseURL = 'https://thoughtsfromtheforeshore.uk/'
languageCode = 'en-gb'
title = 'Thoughts From the Foreshore'
theme = 'hugo-theme-diary'
DefaultContentLanguage = "en"


[params]
favicon = "/favicon.ico"
enablereadingtime = true

[taxonomies]
   category = "categories"
   tag = "tags"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1


[caches]
  [caches.images]
    dir = ':cacheDir/images'
